[package]
name = "winrt-core-app"
version = "0.3.0"
authors = ["Kai <thiskaiguy@gmail.com>"]
edition = "2018"

[dependencies]
atomic = "0.4.5"

[dependencies.winrt]
version = "0.6.0"
features = [
    "windows-applicationmodel",
    "windows-ui",
]

[build-dependencies]
cpp_build = "0.5.1"
